# Generated by Django 4.1.5 on 2023-04-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='slug',
            field=models.SlugField(default=11, unique=True),
            preserve_default=False,
        ),
    ]
