# Generated by Django 4.1.5 on 2023-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('stream', '0002_stream_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='students',
            field=models.ManyToManyField(related_name='students', to='students.student'),
        ),
    ]
